# Generated by Django 3.0.3 on 2020-03-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='name_orig',
            field=models.TextField(blank=True, help_text='Ware (originale Schreibweise)', null=True, verbose_name='Ware (originale Schreibweise)'),
        ),
    ]
