# Generated by Django 3.0.3 on 2020-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0002_ware_name_orig'),
    ]

    operations = [
        migrations.AddField(
            model_name='angabe',
            name='eiskalt',
            field=models.BooleanField(blank=True, default=False, help_text='Eiskalt', null=True, verbose_name='Eiskalt'),
        ),
        migrations.AddField(
            model_name='angabe',
            name='hochwasser',
            field=models.BooleanField(blank=True, default=False, help_text='Hochwasser', null=True, verbose_name='Hochwasser'),
        ),
        migrations.AddField(
            model_name='angabe',
            name='nichts',
            field=models.BooleanField(blank=True, default=False, help_text='Nichts', null=True, verbose_name='Nichts'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='hohenau',
            field=models.BooleanField(blank=True, default=False, help_text='Hohenau', null=True, verbose_name='Hohenau'),
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='zurueck',
            field=models.BooleanField(blank=True, default=False, help_text='zurück', null=True, verbose_name='zurück'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='dreilingsgeld',
            field=models.BooleanField(blank=True, default=False, help_text='Dreilingsgeld', null=True, verbose_name='Dreilingsgeld'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='kammergut',
            field=models.BooleanField(blank=True, default=False, help_text='Kammergut', null=True, verbose_name='Kammergut'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='mautbefreiung',
            field=models.BooleanField(blank=True, default=False, help_text='Mautbefreiung', null=True, verbose_name='Mautbefreiung'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='mautbefreiung_all',
            field=models.BooleanField(blank=True, default=False, help_text='Mautbefreiung', null=True, verbose_name='Mautbefreiung (alle)'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='niederlage',
            field=models.BooleanField(blank=True, default=False, help_text='Niederlage', null=True, verbose_name='Niederlage'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='passbrief',
            field=models.BooleanField(blank=True, default=False, help_text='Passbrief', null=True, verbose_name='Passbrief'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='per_kommission',
            field=models.BooleanField(blank=True, default=False, help_text='Per Kommission', null=True, verbose_name='Per Kommission'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='per_schiffmeister',
            field=models.BooleanField(blank=True, default=False, help_text='Per Schiffmeister', null=True, verbose_name='Per Schiffmeister'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='per_schiffukgut',
            field=models.BooleanField(blank=True, default=False, help_text='Per Schiff UKGut', null=True, verbose_name='Per Schiff UKGut'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='weitertransport',
            field=models.BooleanField(blank=True, default=False, help_text='Weitertransport der Ware', null=True, verbose_name='Weitertransport der Waren'),
        ),
        migrations.AddField(
            model_name='person',
            name='jude',
            field=models.BooleanField(blank=True, default=False, help_text='jüdisch', null=True, verbose_name='jüdisch'),
        ),
        migrations.AddField(
            model_name='person',
            name='weiblich',
            field=models.BooleanField(blank=True, default=False, help_text='weiblich', null=True, verbose_name='weiblich'),
        ),
        migrations.AddField(
            model_name='personangabe',
            name='judenleibmaut',
            field=models.BooleanField(blank=True, default=False, help_text='Judenleibmaut', null=True, verbose_name='Judenleibmaut'),
        ),
        migrations.AddField(
            model_name='personladung',
            name='person_an',
            field=models.BooleanField(blank=True, default=False, help_text='Person (an)', null=True, verbose_name='Person (an)'),
        ),
        migrations.AddField(
            model_name='personladung',
            name='person_einem_dem',
            field=models.BooleanField(blank=True, default=False, help_text='Person (einemDem)', null=True, verbose_name='Person (einemDem)'),
        ),
        migrations.AddField(
            model_name='personladung',
            name='person_per',
            field=models.BooleanField(blank=True, default=False, help_text='Person (per)', null=True, verbose_name='Person (per)'),
        ),
        migrations.AddField(
            model_name='personladung',
            name='person_pro_fur',
            field=models.BooleanField(blank=True, default=False, help_text='Person (pro Für)', null=True, verbose_name='Person (pro Für)'),
        ),
        migrations.AddField(
            model_name='personladung',
            name='person_zugeordnet',
            field=models.BooleanField(blank=True, default=False, help_text='Person (zugeordnet)', null=True, verbose_name='Person (zugeordnet)'),
        ),
    ]
