# Generated by Django 3.0.3 on 2020-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0003_auto_20200310_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='has_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Name'),
        ),
    ]
