# Generated by Django 3.0.3 on 2020-03-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0004_person_has_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrzeug',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_fahrzeug_region_ort', to='aschach.Region', verbose_name='Region'),
        ),
    ]
