# Generated by Django 3.0.3 on 2020-03-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('aschach', '0005_auto_20200312_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wareladung',
            name='maut_d',
            field=models.IntegerField(blank=True, help_text='Maut (d)', null=True, verbose_name='Maut (d)'),
        ),
        migrations.CreateModel(
            name='SchiffTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('leer', models.BooleanField(blank=True, default=False, help_text='leer', null=True, verbose_name='leer')),
                ('geschirr', models.BooleanField(blank=True, default=False, help_text='geschirr', null=True, verbose_name='geschirr')),
                ('rossen', models.BooleanField(blank=True, default=False, help_text='rossen', null=True, verbose_name='rossen')),
                ('mit_sg', models.BooleanField(blank=True, default=False, help_text='mit_sg', null=True, verbose_name='mit_sg')),
                ('mit_sich_selbst', models.BooleanField(blank=True, default=False, help_text='mit_sich_selbst', null=True, verbose_name='mit_sich_selbst')),
                ('fahrzeug', models.ForeignKey(blank=True, help_text='Fahrzeug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_fahrzeug_anzahl', to='aschach.Fahrzeug', verbose_name='Fahrzeug')),
                ('skosconcept', models.ForeignKey(blank=True, help_text='Ladung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_fahrzeugtyp_von', to='vocabs.SkosConcept', verbose_name='Ladung')),
            ],
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='schiff_typ',
            field=models.ManyToManyField(blank=True, help_text='Personen', related_name='rvn_schifftyp', through='aschach.SchiffTyp', to='vocabs.SkosConcept', verbose_name='Personen'),
        ),
    ]
