# Generated by Django 3.0.3 on 2020-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0006_auto_20200322_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='schifftyp',
            name='anzahl',
            field=models.CharField(blank=True, help_text='Anzahl', max_length=250, null=True, verbose_name='Anzahl'),
        ),
    ]
