# Generated by Django 3.0.3 on 2020-03-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('aschach', '0007_schifftyp_anzahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schifftyp',
            name='skosconcept',
            field=models.ForeignKey(blank=True, help_text='Fahrzeugtyp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_fahrzeugtyp_von', to='vocabs.SkosConcept', verbose_name='Fahrzeugtyp'),
        ),
        migrations.CreateModel(
            name='LadungMenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('anzahl', models.CharField(blank=True, help_text='Anzahl der Waren', max_length=250, null=True, verbose_name='Anzahl der Waren')),
                ('anzahl_orig', models.CharField(blank=True, help_text='Anzahl der Waren (wörtlich)', max_length=250, null=True, verbose_name='Anzahl der Waren (wörtlich)')),
                ('einheit', models.ForeignKey(blank=True, help_text='Einheit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ladungmenge_einheit', to='vocabs.SkosConcept', verbose_name='Einheit')),
                ('ladung', models.ForeignKey(blank=True, help_text='Ladung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ladung_menge', to='aschach.Ladung', verbose_name='Ladung')),
                ('ware', models.ForeignKey(blank=True, help_text='Ware', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ware_menge', to='vocabs.SkosConcept', verbose_name='Ware')),
            ],
        ),
        migrations.AddField(
            model_name='ladung',
            name='menge',
            field=models.ManyToManyField(blank=True, help_text='Anzahl/Zusammensetzung der Waren', related_name='rvn_ladung_menge', to='aschach.LadungMenge', verbose_name='Menge'),
        ),
    ]
