# Generated by Django 3.0.3 on 2020-03-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('aschach', '0008_auto_20200324_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='MengeGebinde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('menge', models.CharField(blank=True, help_text='Menge der Wareneingebinden', max_length=250, null=True, verbose_name='Menge der Wareneingebinden')),
                ('anzahl_orig', models.CharField(blank=True, help_text='Menge der Wareneingebinden (wörtlich)', max_length=250, null=True, verbose_name='Menge der Wareneingebinden (wörtlich)')),
                ('gebinde', models.ForeignKey(blank=True, help_text='Gebinde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ladungmenge_einheit', to='vocabs.SkosConcept', verbose_name='Gebinde')),
            ],
        ),
        migrations.RemoveField(
            model_name='ladung',
            name='menge',
        ),
        migrations.DeleteModel(
            name='LadungMenge',
        ),
        migrations.AddField(
            model_name='mengegebinde',
            name='ladung',
            field=models.ForeignKey(blank=True, help_text='Ladung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_ladung_menge', to='aschach.Ladung', verbose_name='Ladung'),
        ),
        migrations.AddField(
            model_name='ladung',
            name='menge_gebinde',
            field=models.ManyToManyField(blank=True, help_text='Anzahl/Zusammensetzung der Waren', related_name='rvn_ladung_menge_gebinde', to='aschach.MengeGebinde', verbose_name='Menge'),
        ),
    ]
