# Generated by Django 3.0.3 on 2020-03-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0009_auto_20200324_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mengegebinde',
            name='anzahl_orig',
        ),
    ]
