# Generated by Django 3.0.3 on 2020-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0010_remove_mengegebinde_anzahl_orig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='donau_normid',
            field=models.IntegerField(blank=True, help_text='Donau Norm (Krems) ID', null=True, verbose_name='Donau Norm (Krems) ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='donau_normid',
            field=models.IntegerField(blank=True, help_text='Donau Norm (Krems) ID', null=True, verbose_name='Donau Norm (Krems) ID'),
        ),
    ]
