# Generated by Django 3.0.3 on 2020-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0011_auto_20200427_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, max_length=300, verbose_name='Normdata URL')),
            ],
            options={
                'verbose_name': 'Normdaten URL',
                'ordering': ['id'],
            },
        ),
    ]
