# Generated by Django 3.0.3 on 2020-04-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0012_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='normdata_url',
            field=models.ManyToManyField(blank=True, help_text='Normdaten URL', related_name='rvn_defines_place', to='aschach.Uri', verbose_name='Normdaten URL'),
        ),
        migrations.AddField(
            model_name='person',
            name='normdata_url',
            field=models.ManyToManyField(blank=True, help_text='Normdaten URL', related_name='rvn_defines_person', to='aschach.Uri', verbose_name='Normdaten URL'),
        ),
    ]
