# Generated by Django 3.0.3 on 2020-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0013_auto_20200427_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Breite (dezimal)', max_digits=19, null=True, verbose_name='Breite'),
        ),
        migrations.AddField(
            model_name='ort',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Länge (dezimal)', max_digits=19, null=True, verbose_name='Länge'),
        ),
    ]
