# Generated by Django 3.0.3 on 2020-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0014_auto_20200427_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='uri',
            name='domain',
            field=models.CharField(blank=True, max_length=300, verbose_name='Normdatequelle'),
        ),
    ]
