# Generated by Django 3.0.3 on 2020-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aschach', '0015_uri_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='uri',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Legacy ID'),
        ),
    ]
