# Generated by Django 4.1.7 on 2023-03-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aschach", "0017_angabe_related_goods_alter_angabe_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="angabe",
            name="related_goods",
        ),
        migrations.AddField(
            model_name="angabe",
            name="related_good",
            field=models.ManyToManyField(
                blank=True,
                help_text="Auflistung der genannten Waren",
                related_name="mentioned_in_Angabe",
                to="aschach.ware",
                verbose_name="Waren",
            ),
        ),
        migrations.AddField(
            model_name="angabe",
            name="related_person",
            field=models.ManyToManyField(
                blank=True,
                help_text="Auflistung der genannten Personen",
                related_name="mentioned_in_Angabe",
                to="aschach.person",
                verbose_name="Person",
            ),
        ),
        migrations.AddField(
            model_name="angabe",
            name="related_place",
            field=models.ManyToManyField(
                blank=True,
                help_text="Auflistung der genannten Ort",
                related_name="mentioned_in_Angabe",
                to="aschach.ort",
                verbose_name="Ort",
            ),
        ),
    ]
