# generated by appcreator
from django.contrib import admin
from . models import (
    Angabe,
    Fahrzeug,
    Firma,
    Ladung,
    NachName,
    Ort,
    Person,
    PersonAngabe,
    PersonLadung,
    PersonenBezeichnung,
    Region,
    Scan,
    VorName,
    Ware,
    WareLadung,
    SchiffTyp,
    MengeGebinde,
)
admin.site.register(MengeGebinde)
admin.site.register(SchiffTyp)
admin.site.register(Angabe)
admin.site.register(Fahrzeug)
admin.site.register(Firma)
admin.site.register(Ladung)
admin.site.register(NachName)
admin.site.register(Ort)
admin.site.register(Person)
admin.site.register(PersonAngabe)
admin.site.register(PersonLadung)
admin.site.register(PersonenBezeichnung)
admin.site.register(Region)
admin.site.register(Scan)
admin.site.register(VorName)
admin.site.register(Ware)
admin.site.register(WareLadung)
