# generated by appcreator
import django_tables2 as tables

from browsing.browsing_utils import MergeColumn
from .models import (
    Angabe,
    Fahrzeug,
    Firma,
    Ladung,
    NachName,
    Ort,
    Person,
    PersonAngabe,
    PersonLadung,
    PersonenBezeichnung,
    Region,
    Scan,
    VorName,
    Ware,
    WareLadung,
)


class AngabeTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    legacy_pk = tables.LinkColumn(verbose_name="Angabe-ID")
    ladung = tables.columns.ManyToManyColumn(verbose_name="Ladung")
    related_good = tables.columns.ManyToManyColumn(verbose_name="Waren")
    related_person = tables.columns.ManyToManyColumn(verbose_name="Personen")
    related_place = tables.columns.ManyToManyColumn(verbose_name="Orte")
    scan = tables.columns.ManyToManyColumn(verbose_name="Scans")

    class Meta:
        model = Angabe
        sequence = ("legacy_pk",)
        attrs = {"class": "table table-responsive table-hover"}


class FahrzeugTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Fahrzeug
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class FirmaTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Firma
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class LadungTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")
    personen = tables.columns.ManyToManyColumn()
    waren = tables.columns.ManyToManyColumn()
    zielort = tables.columns.ManyToManyColumn()
    angabe = tables.columns.TemplateColumn("<a href='{{ record.rvn_angabe_ladung_ladung.first.get_absolute_url }}'>{{ record.rvn_angabe_ladung_ladung.first }}</a>", orderable=False)

    class Meta:
        model = Ladung
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class NachNameTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = NachName
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class OrtTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Ort
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PersonTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")
    verknuepft = tables.columns.ManyToManyColumn()

    class Meta:
        model = Person
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PersonAngabeTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = PersonAngabe
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PersonLadungTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = PersonLadung
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PersonenBezeichnungTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = PersonenBezeichnung
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class RegionTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Region
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class ScanTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Scan
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class VorNameTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = VorName
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class WareTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Ware
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class WareLadungTable(tables.Table):
    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = WareLadung
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}
