# generated by appcreator
from django.urls import path
from . import views
from . import tei_views
from archeutils import views as arche_views

app_name = "aschach"
urlpatterns = [
    path("ids", arche_views.get_ids, name="get_ids"),
    path("arche", arche_views.project_as_arche_graph, name="project_as_arche"),
    path("angabe/", views.AngabeListView.as_view(), name="angabe_browse"),
    path(
        "angabe/detail/<int:pk>",
        views.AngabeDetailView.as_view(),
        name="angabe_detail",
    ),
    path(
        "angabe/arche/<int:pk>",
        arche_views.res_as_arche_graph,
        name="angabe_arche",
    ),
    path("angabe/xml-tei/<int:pk>", tei_views.angabe_as_tei, name="angabe_xml_tei"),
    path("angabe/create/", views.AngabeCreate.as_view(), name="angabe_create"),
    path("angabe/edit/<int:pk>", views.AngabeUpdate.as_view(), name="angabe_edit"),
    path(
        "angabe/delete/<int:pk>",
        views.AngabeDelete.as_view(),
        name="angabe_delete",
    ),
    path("fahrzeug/", views.FahrzeugListView.as_view(), name="fahrzeug_browse"),
    path(
        "fahrzeug/detail/<int:pk>",
        views.FahrzeugDetailView.as_view(),
        name="fahrzeug_detail",
    ),
    path("fahrzeug/create/", views.FahrzeugCreate.as_view(), name="fahrzeug_create"),
    path(
        "fahrzeug/edit/<int:pk>",
        views.FahrzeugUpdate.as_view(),
        name="fahrzeug_edit",
    ),
    path(
        "fahrzeug/delete/<int:pk>",
        views.FahrzeugDelete.as_view(),
        name="fahrzeug_delete",
    ),
    path("firma/", views.FirmaListView.as_view(), name="firma_browse"),
    path(
        "firma/detail/<int:pk>",
        views.FirmaDetailView.as_view(),
        name="firma_detail",
    ),
    path("firma/create/", views.FirmaCreate.as_view(), name="firma_create"),
    path("firma/edit/<int:pk>", views.FirmaUpdate.as_view(), name="firma_edit"),
    path("firma/delete/<int:pk>", views.FirmaDelete.as_view(), name="firma_delete"),
    path("ladung/", views.LadungListView.as_view(), name="ladung_browse"),
    path(
        "ladung/detail/<int:pk>",
        views.LadungDetailView.as_view(),
        name="ladung_detail",
    ),
    path("ladung/create/", views.LadungCreate.as_view(), name="ladung_create"),
    path("ladung/edit/<int:pk>", views.LadungUpdate.as_view(), name="ladung_edit"),
    path(
        "ladung/delete/<int:pk>",
        views.LadungDelete.as_view(),
        name="ladung_delete",
    ),
    path("nachname/", views.NachNameListView.as_view(), name="nachname_browse"),
    path(
        "nachname/detail/<int:pk>",
        views.NachNameDetailView.as_view(),
        name="nachname_detail",
    ),
    path("nachname/create/", views.NachNameCreate.as_view(), name="nachname_create"),
    path(
        "nachname/edit/<int:pk>",
        views.NachNameUpdate.as_view(),
        name="nachname_edit",
    ),
    path(
        "nachname/delete/<int:pk>",
        views.NachNameDelete.as_view(),
        name="nachname_delete",
    ),
    path("ort/", views.OrtListView.as_view(), name="ort_browse"),
    path("ort/detail/<int:pk>", views.OrtDetailView.as_view(), name="ort_detail"),
    path("ort/create/", views.OrtCreate.as_view(), name="ort_create"),
    path("ort/edit/<int:pk>", views.OrtUpdate.as_view(), name="ort_edit"),
    path("ort/delete/<int:pk>", views.OrtDelete.as_view(), name="ort_delete"),
    path("person/", views.PersonListView.as_view(), name="person_browse"),
    path(
        "person/detail/<int:pk>",
        views.PersonDetailView.as_view(),
        name="person_detail",
    ),
    path("person/create/", views.PersonCreate.as_view(), name="person_create"),
    path("person/edit/<int:pk>", views.PersonUpdate.as_view(), name="person_edit"),
    path(
        "person/delete/<int:pk>",
        views.PersonDelete.as_view(),
        name="person_delete",
    ),
    path(
        "personangabe/",
        views.PersonAngabeListView.as_view(),
        name="personangabe_browse",
    ),
    path(
        "personangabe/detail/<int:pk>",
        views.PersonAngabeDetailView.as_view(),
        name="personangabe_detail",
    ),
    path(
        "personangabe/create/",
        views.PersonAngabeCreate.as_view(),
        name="personangabe_create",
    ),
    path(
        "personangabe/edit/<int:pk>",
        views.PersonAngabeUpdate.as_view(),
        name="personangabe_edit",
    ),
    path(
        "personangabe/delete/<int:pk>",
        views.PersonAngabeDelete.as_view(),
        name="personangabe_delete",
    ),
    path(
        "personladung/",
        views.PersonLadungListView.as_view(),
        name="personladung_browse",
    ),
    path(
        "personladung/detail/<int:pk>",
        views.PersonLadungDetailView.as_view(),
        name="personladung_detail",
    ),
    path(
        "personladung/create/",
        views.PersonLadungCreate.as_view(),
        name="personladung_create",
    ),
    path(
        "personladung/edit/<int:pk>",
        views.PersonLadungUpdate.as_view(),
        name="personladung_edit",
    ),
    path(
        "personladung/delete/<int:pk>",
        views.PersonLadungDelete.as_view(),
        name="personladung_delete",
    ),
    path(
        "personenbezeichnung/",
        views.PersonenBezeichnungListView.as_view(),
        name="personenbezeichnung_browse",
    ),
    path(
        "personenbezeichnung/detail/<int:pk>",
        views.PersonenBezeichnungDetailView.as_view(),
        name="personenbezeichnung_detail",
    ),
    path(
        "personenbezeichnung/create/",
        views.PersonenBezeichnungCreate.as_view(),
        name="personenbezeichnung_create",
    ),
    path(
        "personenbezeichnung/edit/<int:pk>",
        views.PersonenBezeichnungUpdate.as_view(),
        name="personenbezeichnung_edit",
    ),
    path(
        "personenbezeichnung/delete/<int:pk>",
        views.PersonenBezeichnungDelete.as_view(),
        name="personenbezeichnung_delete",
    ),
    path("region/", views.RegionListView.as_view(), name="region_browse"),
    path(
        "region/detail/<int:pk>",
        views.RegionDetailView.as_view(),
        name="region_detail",
    ),
    path("region/create/", views.RegionCreate.as_view(), name="region_create"),
    path("region/edit/<int:pk>", views.RegionUpdate.as_view(), name="region_edit"),
    path(
        "region/delete/<int:pk>",
        views.RegionDelete.as_view(),
        name="region_delete",
    ),
    path("scan/", views.ScanListView.as_view(), name="scan_browse"),
    path(
        "scan/detail/<int:pk>",
        views.ScanDetailView.as_view(),
        name="scan_detail",
    ),
    path("scan/create/", views.ScanCreate.as_view(), name="scan_create"),
    path("scan/edit/<int:pk>", views.ScanUpdate.as_view(), name="scan_edit"),
    path("scan/delete/<int:pk>", views.ScanDelete.as_view(), name="scan_delete"),
    path("vorname/", views.VorNameListView.as_view(), name="vorname_browse"),
    path(
        "vorname/detail/<int:pk>",
        views.VorNameDetailView.as_view(),
        name="vorname_detail",
    ),
    path("vorname/create/", views.VorNameCreate.as_view(), name="vorname_create"),
    path(
        "vorname/edit/<int:pk>",
        views.VorNameUpdate.as_view(),
        name="vorname_edit",
    ),
    path(
        "vorname/delete/<int:pk>",
        views.VorNameDelete.as_view(),
        name="vorname_delete",
    ),
    path("ware/", views.WareListView.as_view(), name="ware_browse"),
    path(
        "ware/detail/<int:pk>",
        views.WareDetailView.as_view(),
        name="ware_detail",
    ),
    path("ware/create/", views.WareCreate.as_view(), name="ware_create"),
    path("ware/edit/<int:pk>", views.WareUpdate.as_view(), name="ware_edit"),
    path("ware/delete/<int:pk>", views.WareDelete.as_view(), name="ware_delete"),
    path("wareladung/", views.WareLadungListView.as_view(), name="wareladung_browse"),
    path(
        "wareladung/detail/<int:pk>",
        views.WareLadungDetailView.as_view(),
        name="wareladung_detail",
    ),
    path(
        "wareladung/create/",
        views.WareLadungCreate.as_view(),
        name="wareladung_create",
    ),
    path(
        "wareladung/edit/<int:pk>",
        views.WareLadungUpdate.as_view(),
        name="wareladung_edit",
    ),
    path(
        "wareladung/delete/<int:pk>",
        views.WareLadungDelete.as_view(),
        name="wareladung_delete",
    ),
]
