name: ARCHE-Ingest

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      REDMINE_ID: 21550
      ARCHE_INSTANCE: arche.acdh
      PROJECT_NAME : donauhandel-aschach
      OUTPUT_DIR: to_ingest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Saxon and Ant
      run: pip install requests
    - name: fetch data
      run: python fetch_data.py
    - name: fetch boot.png
      run: wget https://dh-aschach.acdh-dev.oeaw.ac.at/static/webpage/img/boot.png -O to_ingest/boot.png
    - name: ingestion dependencies
      run: composer require "acdh-oeaw/arche-ingest:^1"
    - name: Fetch WF-URL
      run: echo "RUN_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
    - name: ingest arche metadata topcol, col, res
      run: |
        echo 'STEP=Upload AIP to Productive Instance (Apollo)' >> $GITHUB_ENV
        vendor/bin/arche-import-metadata ${OUTPUT_DIR}/arche.ttl https://${ARCHE_INSTANCE}.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --retriesOnConflict 25
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID 'Upload AIP to Productive Instance (Apollo)'
    - name: cache AV database
      id: avdb
      uses: actions/cache@v3
      with:
        path: ~/.cvdupdate
        key: constant
    - name: refresh AV database
      run: |
        python3 -m pip install --user cvdupdate && cvd update
    - name: run repo-file-checker
      run: |
        echo 'STEP=Run repo-file-checker' >> $GITHUB_ENV
        docker run --rm -d --name filechecker -v `pwd`/filechecker/reports:/reports -v `pwd`/to_ingest:/data -v ~/.cvdupdate/database/:/var/lib/clamav -e DAEMONIZE=1 acdhch/arche-filechecker 0
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID 'Virus scan'
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID 'Run repo-file-checker'
    - name: ingest binaries
      run: |
        echo 'STEP=Upload Binaries' >> $GITHUB_ENV
        vendor/bin/arche-import-binary to_ingest https://id.acdh.oeaw.ac.at/${PROJECT_NAME} https://${ARCHE_INSTANCE}.oeaw.ac.at/api ${{secrets.ARCHE_LOGIN}} ${{secrets.ARCHE_PASSWORD}} --skip not_exist
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" $REDMINE_ID 'Upload AIP to Productive Instance (Apollo)'
    - name: on failure
      if: ${{ failure() }}
      run: |
        vendor/bin/arche-update-redmine --token ${{ secrets.REDMINE_TOKEN }} --append "$RUN_URL" --statusCode 1 $REDMINE_ID "$STEP"
